/*
 * generated by Xtext 2.23.0
 */
package hu.sze.aut.robot.kinematic.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class KinematicDslUiModule extends AbstractKinematicDslUiModule {

	public KinematicDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
