/*
 * generated by Xtext 2.23.0
 */
package hu.sze.aut.robotics.vehicle.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class VehicleDslUiModule extends AbstractVehicleDslUiModule {

	public VehicleDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
