/*
 * generated by Xtext 2.25.0
 */
package hu.sze.aut.robot.kinematic.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import hu.sze.aut.robot.kinematic.ide.contentassist.antlr.internal.InternalKinematicDslParser;
import hu.sze.aut.robot.kinematic.services.KinematicDslGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class KinematicDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(KinematicDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, KinematicDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getRootElementAccess().getAlternatives(), "rule__RootElement__Alternatives");
			builder.put(grammarAccess.getControlModelAccess().getAlternatives(), "rule__ControlModel__Alternatives");
			builder.put(grammarAccess.getSensorAccess().getAlternatives(), "rule__Sensor__Alternatives");
			builder.put(grammarAccess.getKinematicModuleAccess().getAlternatives(), "rule__KinematicModule__Alternatives");
			builder.put(grammarAccess.getGeometryDescriptionAccess().getAlternatives(), "rule__GeometryDescription__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getJointAccess().getAlternatives(), "rule__Joint__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
			builder.put(grammarAccess.getJointControlTypeAccess().getAlternatives(), "rule__JointControlType__Alternatives");
			builder.put(grammarAccess.getJointTypeAccess().getAlternatives(), "rule__JointType__Alternatives");
			builder.put(grammarAccess.getKinematicModule_ImplAccess().getGroup(), "rule__KinematicModule_Impl__Group__0");
			builder.put(grammarAccess.getKinematicModule_ImplAccess().getGroup_4(), "rule__KinematicModule_Impl__Group_4__0");
			builder.put(grammarAccess.getKinematicModule_ImplAccess().getGroup_5(), "rule__KinematicModule_Impl__Group_5__0");
			builder.put(grammarAccess.getKinematicModule_ImplAccess().getGroup_6(), "rule__KinematicModule_Impl__Group_6__0");
			builder.put(grammarAccess.getKinematicModule_ImplAccess().getGroup_7(), "rule__KinematicModule_Impl__Group_7__0");
			builder.put(grammarAccess.getRobotAccess().getGroup(), "rule__Robot__Group__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_6(), "rule__Robot__Group_6__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_6_1(), "rule__Robot__Group_6_1__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_8(), "rule__Robot__Group_8__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_9(), "rule__Robot__Group_9__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_10(), "rule__Robot__Group_10__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_11(), "rule__Robot__Group_11__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_12(), "rule__Robot__Group_12__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_13(), "rule__Robot__Group_13__0");
			builder.put(grammarAccess.getDifferentialControlModelAccess().getGroup(), "rule__DifferentialControlModel__Group__0");
			builder.put(grammarAccess.getCustomControlModelAccess().getGroup(), "rule__CustomControlModel__Group__0");
			builder.put(grammarAccess.getLidarAccess().getGroup(), "rule__Lidar__Group__0");
			builder.put(grammarAccess.getRangeDefinitionAccess().getGroup(), "rule__RangeDefinition__Group__0");
			builder.put(grammarAccess.getBeamDefinitionAccess().getGroup(), "rule__BeamDefinition__Group__0");
			builder.put(grammarAccess.getCameraAccess().getGroup(), "rule__Camera__Group__0");
			builder.put(grammarAccess.getCameraObjectiveAccess().getGroup(), "rule__CameraObjective__Group__0");
			builder.put(grammarAccess.getScannerAccess().getGroup(), "rule__Scanner__Group__0");
			builder.put(grammarAccess.getGpsSensorAccess().getGroup(), "rule__GpsSensor__Group__0");
			builder.put(grammarAccess.getImuSensorAccess().getGroup(), "rule__ImuSensor__Group__0");
			builder.put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_3(), "rule__Link__Group_3__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_5(), "rule__Link__Group_5__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_6(), "rule__Link__Group_6__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_7(), "rule__Link__Group_7__0");
			builder.put(grammarAccess.getTransationalFrictionAccess().getGroup(), "rule__TransationalFriction__Group__0");
			builder.put(grammarAccess.getTorsionalFrictionAccess().getGroup(), "rule__TorsionalFriction__Group__0");
			builder.put(grammarAccess.getJoint_IMPLAccess().getGroup(), "rule__Joint_IMPL__Group__0");
			builder.put(grammarAccess.getJoint_IMPLAccess().getGroup_6(), "rule__Joint_IMPL__Group_6__0");
			builder.put(grammarAccess.getJoint_IMPLAccess().getGroup_7(), "rule__Joint_IMPL__Group_7__0");
			builder.put(grammarAccess.getJoint_IMPLAccess().getGroup_11(), "rule__Joint_IMPL__Group_11__0");
			builder.put(grammarAccess.getSpringJointAccess().getGroup(), "rule__SpringJoint__Group__0");
			builder.put(grammarAccess.getSpringJointAccess().getGroup_6(), "rule__SpringJoint__Group_6__0");
			builder.put(grammarAccess.getSpringJointAccess().getGroup_7(), "rule__SpringJoint__Group_7__0");
			builder.put(grammarAccess.getSpringJointAccess().getGroup_11(), "rule__SpringJoint__Group_11__0");
			builder.put(grammarAccess.getJointControlAccess().getGroup(), "rule__JointControl__Group__0");
			builder.put(grammarAccess.getTemplateInstantiationAccess().getGroup(), "rule__TemplateInstantiation__Group__0");
			builder.put(grammarAccess.getPoseAccess().getGroup(), "rule__Pose__Group__0");
			builder.put(grammarAccess.getPoseAccess().getGroup_3(), "rule__Pose__Group_3__0");
			builder.put(grammarAccess.getInertiaAccess().getGroup(), "rule__Inertia__Group__0");
			builder.put(grammarAccess.getInertiaAccess().getGroup_5(), "rule__Inertia__Group_5__0");
			builder.put(grammarAccess.getInertiaMatrixAccess().getGroup(), "rule__InertiaMatrix__Group__0");
			builder.put(grammarAccess.getInertiaMatrixAccess().getGroup_3(), "rule__InertiaMatrix__Group_3__0");
			builder.put(grammarAccess.getInertiaMatrixAccess().getGroup_4(), "rule__InertiaMatrix__Group_4__0");
			builder.put(grammarAccess.getInertiaMatrixAccess().getGroup_6(), "rule__InertiaMatrix__Group_6__0");
			builder.put(grammarAccess.getInertiaMatrixAccess().getGroup_6_1(), "rule__InertiaMatrix__Group_6_1__0");
			builder.put(grammarAccess.getInertiaMatrixAccess().getGroup_6_2(), "rule__InertiaMatrix__Group_6_2__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getCollisionAccess().getGroup(), "rule__Collision__Group__0");
			builder.put(grammarAccess.getCollisionAccess().getGroup_2(), "rule__Collision__Group_2__0");
			builder.put(grammarAccess.getVisualAccess().getGroup(), "rule__Visual__Group__0");
			builder.put(grammarAccess.getVisualAccess().getGroup_2(), "rule__Visual__Group_2__0");
			builder.put(grammarAccess.getRotationAccess().getGroup(), "rule__Rotation__Group__0");
			builder.put(grammarAccess.getRotationAccess().getGroup_1(), "rule__Rotation__Group_1__0");
			builder.put(grammarAccess.getRotationAccess().getGroup_2(), "rule__Rotation__Group_2__0");
			builder.put(grammarAccess.getPositionAccess().getGroup(), "rule__Position__Group__0");
			builder.put(grammarAccess.getPositionAccess().getGroup_1(), "rule__Position__Group_1__0");
			builder.put(grammarAccess.getPositionAccess().getGroup_2(), "rule__Position__Group_2__0");
			builder.put(grammarAccess.getMeshAccess().getGroup(), "rule__Mesh__Group__0");
			builder.put(grammarAccess.getMeshAccess().getGroup_4(), "rule__Mesh__Group_4__0");
			builder.put(grammarAccess.getCubeAccess().getGroup(), "rule__Cube__Group__0");
			builder.put(grammarAccess.getCylinderAccess().getGroup(), "rule__Cylinder__Group__0");
			builder.put(grammarAccess.getCylinderAccess().getGroup_3(), "rule__Cylinder__Group_3__0");
			builder.put(grammarAccess.getSphereAccess().getGroup(), "rule__Sphere__Group__0");
			builder.put(grammarAccess.getSphereAccess().getGroup_2(), "rule__Sphere__Group_2__0");
			builder.put(grammarAccess.getJointConstraintsAccess().getGroup(), "rule__JointConstraints__Group__0");
			builder.put(grammarAccess.getJointConstraintsAccess().getGroup_2(), "rule__JointConstraints__Group_2__0");
			builder.put(grammarAccess.getJointConstraintsAccess().getGroup_3(), "rule__JointConstraints__Group_3__0");
			builder.put(grammarAccess.getAxisAccess().getGroup(), "rule__Axis__Group__0");
			builder.put(grammarAccess.getKinematicModule_ImplAccess().getNameAssignment_2(), "rule__KinematicModule_Impl__NameAssignment_2");
			builder.put(grammarAccess.getKinematicModule_ImplAccess().getLinkAssignment_4_0(), "rule__KinematicModule_Impl__LinkAssignment_4_0");
			builder.put(grammarAccess.getKinematicModule_ImplAccess().getLinkAssignment_4_1(), "rule__KinematicModule_Impl__LinkAssignment_4_1");
			builder.put(grammarAccess.getKinematicModule_ImplAccess().getRoot_elementAssignment_5_1(), "rule__KinematicModule_Impl__Root_elementAssignment_5_1");
			builder.put(grammarAccess.getKinematicModule_ImplAccess().getJointAssignment_6_0(), "rule__KinematicModule_Impl__JointAssignment_6_0");
			builder.put(grammarAccess.getKinematicModule_ImplAccess().getJointAssignment_6_1(), "rule__KinematicModule_Impl__JointAssignment_6_1");
			builder.put(grammarAccess.getKinematicModule_ImplAccess().getSensorAssignment_7_0(), "rule__KinematicModule_Impl__SensorAssignment_7_0");
			builder.put(grammarAccess.getKinematicModule_ImplAccess().getSensorAssignment_7_1(), "rule__KinematicModule_Impl__SensorAssignment_7_1");
			builder.put(grammarAccess.getRobotAccess().getDescription_packageAssignment_2(), "rule__Robot__Description_packageAssignment_2");
			builder.put(grammarAccess.getRobotAccess().getNameAssignment_4(), "rule__Robot__NameAssignment_4");
			builder.put(grammarAccess.getRobotAccess().getDescription_formatAssignment_6_0(), "rule__Robot__Description_formatAssignment_6_0");
			builder.put(grammarAccess.getRobotAccess().getDescription_formatAssignment_6_1_1(), "rule__Robot__Description_formatAssignment_6_1_1");
			builder.put(grammarAccess.getRobotAccess().getLinkAssignment_8_0(), "rule__Robot__LinkAssignment_8_0");
			builder.put(grammarAccess.getRobotAccess().getLinkAssignment_8_1(), "rule__Robot__LinkAssignment_8_1");
			builder.put(grammarAccess.getRobotAccess().getRoot_elementAssignment_9_1(), "rule__Robot__Root_elementAssignment_9_1");
			builder.put(grammarAccess.getRobotAccess().getJointAssignment_10_0(), "rule__Robot__JointAssignment_10_0");
			builder.put(grammarAccess.getRobotAccess().getJointAssignment_10_1(), "rule__Robot__JointAssignment_10_1");
			builder.put(grammarAccess.getRobotAccess().getSensorAssignment_11_0(), "rule__Robot__SensorAssignment_11_0");
			builder.put(grammarAccess.getRobotAccess().getSensorAssignment_11_1(), "rule__Robot__SensorAssignment_11_1");
			builder.put(grammarAccess.getRobotAccess().getTemplateinstantiationAssignment_12_0(), "rule__Robot__TemplateinstantiationAssignment_12_0");
			builder.put(grammarAccess.getRobotAccess().getTemplateinstantiationAssignment_12_1(), "rule__Robot__TemplateinstantiationAssignment_12_1");
			builder.put(grammarAccess.getRobotAccess().getControlmodelAssignment_13_1(), "rule__Robot__ControlmodelAssignment_13_1");
			builder.put(grammarAccess.getDifferentialControlModelAccess().getLeft_jointAssignment_3(), "rule__DifferentialControlModel__Left_jointAssignment_3");
			builder.put(grammarAccess.getDifferentialControlModelAccess().getRight_jointAssignment_5(), "rule__DifferentialControlModel__Right_jointAssignment_5");
			builder.put(grammarAccess.getDifferentialControlModelAccess().getWheel_separationAssignment_8(), "rule__DifferentialControlModel__Wheel_separationAssignment_8");
			builder.put(grammarAccess.getDifferentialControlModelAccess().getWheel_diameterAssignment_10(), "rule__DifferentialControlModel__Wheel_diameterAssignment_10");
			builder.put(grammarAccess.getLidarAccess().getParentAssignment_1(), "rule__Lidar__ParentAssignment_1");
			builder.put(grammarAccess.getLidarAccess().getNamespaceAssignment_4(), "rule__Lidar__NamespaceAssignment_4");
			builder.put(grammarAccess.getLidarAccess().getNameAssignment_6(), "rule__Lidar__NameAssignment_6");
			builder.put(grammarAccess.getLidarAccess().getTopic_nameAssignment_8(), "rule__Lidar__Topic_nameAssignment_8");
			builder.put(grammarAccess.getLidarAccess().getFreqAssignment_10(), "rule__Lidar__FreqAssignment_10");
			builder.put(grammarAccess.getLidarAccess().getHorizontalAssignment_14(), "rule__Lidar__HorizontalAssignment_14");
			builder.put(grammarAccess.getLidarAccess().getVerticalAssignment_16(), "rule__Lidar__VerticalAssignment_16");
			builder.put(grammarAccess.getLidarAccess().getRangeAssignment_18(), "rule__Lidar__RangeAssignment_18");
			builder.put(grammarAccess.getRangeDefinitionAccess().getMin_rangeAssignment_2(), "rule__RangeDefinition__Min_rangeAssignment_2");
			builder.put(grammarAccess.getRangeDefinitionAccess().getMax_rangeAssignment_4(), "rule__RangeDefinition__Max_rangeAssignment_4");
			builder.put(grammarAccess.getBeamDefinitionAccess().getMin_angleAssignment_2(), "rule__BeamDefinition__Min_angleAssignment_2");
			builder.put(grammarAccess.getBeamDefinitionAccess().getMax_angleAssignment_4(), "rule__BeamDefinition__Max_angleAssignment_4");
			builder.put(grammarAccess.getBeamDefinitionAccess().getResolutionAssignment_8(), "rule__BeamDefinition__ResolutionAssignment_8");
			builder.put(grammarAccess.getBeamDefinitionAccess().getSamplesAssignment_10(), "rule__BeamDefinition__SamplesAssignment_10");
			builder.put(grammarAccess.getCameraAccess().getParentAssignment_1(), "rule__Camera__ParentAssignment_1");
			builder.put(grammarAccess.getCameraAccess().getNamespaceAssignment_4(), "rule__Camera__NamespaceAssignment_4");
			builder.put(grammarAccess.getCameraAccess().getNameAssignment_6(), "rule__Camera__NameAssignment_6");
			builder.put(grammarAccess.getCameraAccess().getTopic_nameAssignment_8(), "rule__Camera__Topic_nameAssignment_8");
			builder.put(grammarAccess.getCameraAccess().getFreqAssignment_10(), "rule__Camera__FreqAssignment_10");
			builder.put(grammarAccess.getCameraAccess().getCameraobjectiveAssignment_13(), "rule__Camera__CameraobjectiveAssignment_13");
			builder.put(grammarAccess.getCameraAccess().getCameraobjectiveAssignment_14(), "rule__Camera__CameraobjectiveAssignment_14");
			builder.put(grammarAccess.getCameraObjectiveAccess().getNameAssignment_2(), "rule__CameraObjective__NameAssignment_2");
			builder.put(grammarAccess.getCameraObjectiveAccess().getFovAssignment_4(), "rule__CameraObjective__FovAssignment_4");
			builder.put(grammarAccess.getCameraObjectiveAccess().getClip_nearAssignment_7(), "rule__CameraObjective__Clip_nearAssignment_7");
			builder.put(grammarAccess.getCameraObjectiveAccess().getClip_farAssignment_9(), "rule__CameraObjective__Clip_farAssignment_9");
			builder.put(grammarAccess.getCameraObjectiveAccess().getImage_widthAssignment_13(), "rule__CameraObjective__Image_widthAssignment_13");
			builder.put(grammarAccess.getCameraObjectiveAccess().getImage_heightAssignment_15(), "rule__CameraObjective__Image_heightAssignment_15");
			builder.put(grammarAccess.getCameraObjectiveAccess().getOffsetAssignment_18(), "rule__CameraObjective__OffsetAssignment_18");
			builder.put(grammarAccess.getScannerAccess().getParentAssignment_1(), "rule__Scanner__ParentAssignment_1");
			builder.put(grammarAccess.getScannerAccess().getNamespaceAssignment_4(), "rule__Scanner__NamespaceAssignment_4");
			builder.put(grammarAccess.getScannerAccess().getNameAssignment_6(), "rule__Scanner__NameAssignment_6");
			builder.put(grammarAccess.getScannerAccess().getTopic_nameAssignment_8(), "rule__Scanner__Topic_nameAssignment_8");
			builder.put(grammarAccess.getScannerAccess().getFreqAssignment_10(), "rule__Scanner__FreqAssignment_10");
			builder.put(grammarAccess.getScannerAccess().getHorizontalAssignment_14(), "rule__Scanner__HorizontalAssignment_14");
			builder.put(grammarAccess.getScannerAccess().getRangeAssignment_16(), "rule__Scanner__RangeAssignment_16");
			builder.put(grammarAccess.getGpsSensorAccess().getParentAssignment_1(), "rule__GpsSensor__ParentAssignment_1");
			builder.put(grammarAccess.getGpsSensorAccess().getNamespaceAssignment_4(), "rule__GpsSensor__NamespaceAssignment_4");
			builder.put(grammarAccess.getGpsSensorAccess().getNameAssignment_6(), "rule__GpsSensor__NameAssignment_6");
			builder.put(grammarAccess.getGpsSensorAccess().getTopic_nameAssignment_8(), "rule__GpsSensor__Topic_nameAssignment_8");
			builder.put(grammarAccess.getGpsSensorAccess().getFreqAssignment_11(), "rule__GpsSensor__FreqAssignment_11");
			builder.put(grammarAccess.getImuSensorAccess().getParentAssignment_1(), "rule__ImuSensor__ParentAssignment_1");
			builder.put(grammarAccess.getImuSensorAccess().getNamespaceAssignment_4(), "rule__ImuSensor__NamespaceAssignment_4");
			builder.put(grammarAccess.getImuSensorAccess().getNameAssignment_6(), "rule__ImuSensor__NameAssignment_6");
			builder.put(grammarAccess.getImuSensorAccess().getTopic_nameAssignment_8(), "rule__ImuSensor__Topic_nameAssignment_8");
			builder.put(grammarAccess.getImuSensorAccess().getFreqAssignment_11(), "rule__ImuSensor__FreqAssignment_11");
			builder.put(grammarAccess.getLinkAccess().getNameAssignment_2(), "rule__Link__NameAssignment_2");
			builder.put(grammarAccess.getLinkAccess().getPoseAssignment_3_1(), "rule__Link__PoseAssignment_3_1");
			builder.put(grammarAccess.getLinkAccess().getInertiaAssignment_5_0(), "rule__Link__InertiaAssignment_5_0");
			builder.put(grammarAccess.getLinkAccess().getInertiaAssignment_5_1(), "rule__Link__InertiaAssignment_5_1");
			builder.put(grammarAccess.getLinkAccess().getCollisionAssignment_6_0(), "rule__Link__CollisionAssignment_6_0");
			builder.put(grammarAccess.getLinkAccess().getCollisionAssignment_6_1(), "rule__Link__CollisionAssignment_6_1");
			builder.put(grammarAccess.getLinkAccess().getVisualAssignment_7_0(), "rule__Link__VisualAssignment_7_0");
			builder.put(grammarAccess.getLinkAccess().getVisualAssignment_7_1(), "rule__Link__VisualAssignment_7_1");
			builder.put(grammarAccess.getTransationalFrictionAccess().getMuAssignment_3(), "rule__TransationalFriction__MuAssignment_3");
			builder.put(grammarAccess.getTransationalFrictionAccess().getMu2Assignment_5(), "rule__TransationalFriction__Mu2Assignment_5");
			builder.put(grammarAccess.getTransationalFrictionAccess().getAxisAssignment_7(), "rule__TransationalFriction__AxisAssignment_7");
			builder.put(grammarAccess.getTorsionalFrictionAccess().getCoeffictientAssignment_3(), "rule__TorsionalFriction__CoeffictientAssignment_3");
			builder.put(grammarAccess.getTorsionalFrictionAccess().getPatch_radiusAssignment_7(), "rule__TorsionalFriction__Patch_radiusAssignment_7");
			builder.put(grammarAccess.getJoint_IMPLAccess().getParentAssignment_1(), "rule__Joint_IMPL__ParentAssignment_1");
			builder.put(grammarAccess.getJoint_IMPLAccess().getChildAssignment_3(), "rule__Joint_IMPL__ChildAssignment_3");
			builder.put(grammarAccess.getJoint_IMPLAccess().getJointtypeAssignment_4(), "rule__Joint_IMPL__JointtypeAssignment_4");
			builder.put(grammarAccess.getJoint_IMPLAccess().getNameAssignment_5(), "rule__Joint_IMPL__NameAssignment_5");
			builder.put(grammarAccess.getJoint_IMPLAccess().getDampingAssignment_6_2(), "rule__Joint_IMPL__DampingAssignment_6_2");
			builder.put(grammarAccess.getJoint_IMPLAccess().getFrictionAssignment_6_4(), "rule__Joint_IMPL__FrictionAssignment_6_4");
			builder.put(grammarAccess.getJoint_IMPLAccess().getPoseAssignment_7_1(), "rule__Joint_IMPL__PoseAssignment_7_1");
			builder.put(grammarAccess.getJoint_IMPLAccess().getAxisAssignment_8(), "rule__Joint_IMPL__AxisAssignment_8");
			builder.put(grammarAccess.getJoint_IMPLAccess().getJointcontrolAssignment_10(), "rule__Joint_IMPL__JointcontrolAssignment_10");
			builder.put(grammarAccess.getJoint_IMPLAccess().getJointconstraintsAssignment_11_1(), "rule__Joint_IMPL__JointconstraintsAssignment_11_1");
			builder.put(grammarAccess.getSpringJointAccess().getParentAssignment_1(), "rule__SpringJoint__ParentAssignment_1");
			builder.put(grammarAccess.getSpringJointAccess().getChildAssignment_3(), "rule__SpringJoint__ChildAssignment_3");
			builder.put(grammarAccess.getSpringJointAccess().getJointtypeAssignment_4(), "rule__SpringJoint__JointtypeAssignment_4");
			builder.put(grammarAccess.getSpringJointAccess().getNameAssignment_5(), "rule__SpringJoint__NameAssignment_5");
			builder.put(grammarAccess.getSpringJointAccess().getDampingAssignment_6_2(), "rule__SpringJoint__DampingAssignment_6_2");
			builder.put(grammarAccess.getSpringJointAccess().getFrictionAssignment_6_4(), "rule__SpringJoint__FrictionAssignment_6_4");
			builder.put(grammarAccess.getSpringJointAccess().getPoseAssignment_7_1(), "rule__SpringJoint__PoseAssignment_7_1");
			builder.put(grammarAccess.getSpringJointAccess().getAxisAssignment_8(), "rule__SpringJoint__AxisAssignment_8");
			builder.put(grammarAccess.getSpringJointAccess().getJointcontrolAssignment_10(), "rule__SpringJoint__JointcontrolAssignment_10");
			builder.put(grammarAccess.getSpringJointAccess().getJointconstraintsAssignment_11_1(), "rule__SpringJoint__JointconstraintsAssignment_11_1");
			builder.put(grammarAccess.getSpringJointAccess().getStiffnessAssignment_16(), "rule__SpringJoint__StiffnessAssignment_16");
			builder.put(grammarAccess.getSpringJointAccess().getLimit_stiffnessAssignment_18(), "rule__SpringJoint__Limit_stiffnessAssignment_18");
			builder.put(grammarAccess.getSpringJointAccess().getPos_referenceAssignment_22(), "rule__SpringJoint__Pos_referenceAssignment_22");
			builder.put(grammarAccess.getSpringJointAccess().getLimit_referenceAssignment_24(), "rule__SpringJoint__Limit_referenceAssignment_24");
			builder.put(grammarAccess.getJointControlAccess().getTypeAssignment_3(), "rule__JointControl__TypeAssignment_3");
			builder.put(grammarAccess.getTemplateInstantiationAccess().getInvertAssignment_1(), "rule__TemplateInstantiation__InvertAssignment_1");
			builder.put(grammarAccess.getTemplateInstantiationAccess().getLinkAssignment_3(), "rule__TemplateInstantiation__LinkAssignment_3");
			builder.put(grammarAccess.getTemplateInstantiationAccess().getNameAssignment_5(), "rule__TemplateInstantiation__NameAssignment_5");
			builder.put(grammarAccess.getTemplateInstantiationAccess().getKinematicmoduleAssignment_7(), "rule__TemplateInstantiation__KinematicmoduleAssignment_7");
			builder.put(grammarAccess.getTemplateInstantiationAccess().getPoseAssignment_10(), "rule__TemplateInstantiation__PoseAssignment_10");
			builder.put(grammarAccess.getPoseAccess().getPositionAssignment_2(), "rule__Pose__PositionAssignment_2");
			builder.put(grammarAccess.getPoseAccess().getRotationAssignment_3_1(), "rule__Pose__RotationAssignment_3_1");
			builder.put(grammarAccess.getInertiaAccess().getMassAssignment_3(), "rule__Inertia__MassAssignment_3");
			builder.put(grammarAccess.getInertiaAccess().getInertiamatrixAssignment_4(), "rule__Inertia__InertiamatrixAssignment_4");
			builder.put(grammarAccess.getInertiaAccess().getPoseAssignment_5_1(), "rule__Inertia__PoseAssignment_5_1");
			builder.put(grammarAccess.getInertiaMatrixAccess().getIxxAssignment_3_0(), "rule__InertiaMatrix__IxxAssignment_3_0");
			builder.put(grammarAccess.getInertiaMatrixAccess().getIyyAssignment_4_0(), "rule__InertiaMatrix__IyyAssignment_4_0");
			builder.put(grammarAccess.getInertiaMatrixAccess().getIzzAssignment_5(), "rule__InertiaMatrix__IzzAssignment_5");
			builder.put(grammarAccess.getInertiaMatrixAccess().getIxyAssignment_6_1_0(), "rule__InertiaMatrix__IxyAssignment_6_1_0");
			builder.put(grammarAccess.getInertiaMatrixAccess().getIxzAssignment_6_2_0(), "rule__InertiaMatrix__IxzAssignment_6_2_0");
			builder.put(grammarAccess.getInertiaMatrixAccess().getIyzAssignment_6_3(), "rule__InertiaMatrix__IyzAssignment_6_3");
			builder.put(grammarAccess.getCollisionAccess().getOffsetAssignment_2_2(), "rule__Collision__OffsetAssignment_2_2");
			builder.put(grammarAccess.getCollisionAccess().getGeometrydescriptionAssignment_4(), "rule__Collision__GeometrydescriptionAssignment_4");
			builder.put(grammarAccess.getVisualAccess().getOffsetAssignment_2_2(), "rule__Visual__OffsetAssignment_2_2");
			builder.put(grammarAccess.getVisualAccess().getGeometrydescriptionAssignment_4(), "rule__Visual__GeometrydescriptionAssignment_4");
			builder.put(grammarAccess.getRotationAccess().getRollAssignment_1_0(), "rule__Rotation__RollAssignment_1_0");
			builder.put(grammarAccess.getRotationAccess().getPitchAssignment_2_0(), "rule__Rotation__PitchAssignment_2_0");
			builder.put(grammarAccess.getRotationAccess().getYawAssignment_3(), "rule__Rotation__YawAssignment_3");
			builder.put(grammarAccess.getPositionAccess().getXAssignment_1_0(), "rule__Position__XAssignment_1_0");
			builder.put(grammarAccess.getPositionAccess().getYAssignment_2_0(), "rule__Position__YAssignment_2_0");
			builder.put(grammarAccess.getPositionAccess().getZAssignment_3(), "rule__Position__ZAssignment_3");
			builder.put(grammarAccess.getMeshAccess().getFilepathAssignment_3(), "rule__Mesh__FilepathAssignment_3");
			builder.put(grammarAccess.getMeshAccess().getSxAssignment_4_1(), "rule__Mesh__SxAssignment_4_1");
			builder.put(grammarAccess.getMeshAccess().getSyAssignment_4_3(), "rule__Mesh__SyAssignment_4_3");
			builder.put(grammarAccess.getMeshAccess().getSzAssignment_4_5(), "rule__Mesh__SzAssignment_4_5");
			builder.put(grammarAccess.getCubeAccess().getSxAssignment_3(), "rule__Cube__SxAssignment_3");
			builder.put(grammarAccess.getCubeAccess().getSyAssignment_5(), "rule__Cube__SyAssignment_5");
			builder.put(grammarAccess.getCubeAccess().getSzAssignment_7(), "rule__Cube__SzAssignment_7");
			builder.put(grammarAccess.getCylinderAccess().getRadiusAssignment_3_0(), "rule__Cylinder__RadiusAssignment_3_0");
			builder.put(grammarAccess.getCylinderAccess().getHeightAssignment_4(), "rule__Cylinder__HeightAssignment_4");
			builder.put(grammarAccess.getSphereAccess().getRadiusAssignment_2_1(), "rule__Sphere__RadiusAssignment_2_1");
			builder.put(grammarAccess.getJointConstraintsAccess().getMin_limitAssignment_2_1(), "rule__JointConstraints__Min_limitAssignment_2_1");
			builder.put(grammarAccess.getJointConstraintsAccess().getMax_limitAssignment_3_0(), "rule__JointConstraints__Max_limitAssignment_3_0");
			builder.put(grammarAccess.getAxisAccess().getAxAssignment_3(), "rule__Axis__AxAssignment_3");
			builder.put(grammarAccess.getAxisAccess().getAyAssignment_5(), "rule__Axis__AyAssignment_5");
			builder.put(grammarAccess.getAxisAccess().getAzAssignment_7(), "rule__Axis__AzAssignment_7");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private KinematicDslGrammarAccess grammarAccess;

	@Override
	protected InternalKinematicDslParser createParser() {
		InternalKinematicDslParser result = new InternalKinematicDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public KinematicDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KinematicDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
