/*
 * generated by Xtext 2.25.0
 */
package hu.sze.aut.robotlabor.scene.description.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SceneDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("hu/sze/aut/robotlabor/scene/description/parser/antlr/internal/InternalSceneDsl.tokens");
	}
}
