/*
 * generated by Xtext 2.25.0
 */
package hu.sze.aut.robotlabor.scene.description.parser.antlr;

import com.google.inject.Inject;
import hu.sze.aut.robotlabor.scene.description.parser.antlr.internal.InternalSceneDslParser;
import hu.sze.aut.robotlabor.scene.description.services.SceneDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SceneDslParser extends AbstractAntlrParser {

	@Inject
	private SceneDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSceneDslParser createParser(XtextTokenStream stream) {
		return new InternalSceneDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RootElement";
	}

	public SceneDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SceneDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
