/*
 * generated by Xtext 2.23.0
 */
package hu.sze.aut.robotics.vehicle.ide;


/**
 * Use this class to register ide components.
 */
public class VehicleDslIdeModule extends AbstractVehicleDslIdeModule {
}
