/*
 * generated by Xtext 2.25.0
 */
package hu.sze.aut.robotlabor.scene.description.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SceneDslUiModule extends AbstractSceneDslUiModule {

	public SceneDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
