/*
 * generated by Xtext 2.23.0
 */
package hu.sze.aut.robot.kinematic.ide;


/**
 * Use this class to register ide components.
 */
public class KinematicDslIdeModule extends AbstractKinematicDslIdeModule {
}
