/*
 * generated by Xtext 2.23.0
 */
package hu.sze.aut.robot.description.scene.ide;


/**
 * Use this class to register ide components.
 */
public class SceneDslIdeModule extends AbstractSceneDslIdeModule {
}
