/*
 * generated by Xtext 2.25.0
 */
package hu.sze.aut.robotlabor.scene.description.ui.tests;

import com.google.inject.Injector;
import hu.sze.aut.robotlabor.scene.description.scenedsl.ui.internal.ScenedslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SceneDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ScenedslActivator.getInstance().getInjector("hu.sze.aut.robotlabor.scene.description.SceneDsl");
	}

}
