/*
 * generated by Xtext 2.25.0
 */
package hu.sze.aut.robot.kinematic.ui.tests;

import com.google.inject.Injector;
import hu.sze.aut.robot.kinematic.kinematicdsl.ui.internal.KinematicdslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class KinematicDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return KinematicdslActivator.getInstance().getInjector("hu.sze.aut.robot.kinematic.KinematicDsl");
	}

}
