/*
 * generated by Xtext 2.25.0
 */
package hu.sze.aut.robotlabor.scene.description.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSceneDslScopeProvider extends DelegatingScopeProvider {
}
