/*
 * generated by Xtext 2.25.0
 */
package hu.sze.aut.robotlabor.scene.description.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import hu.sze.aut.robotlabor.scene.description.ide.contentassist.antlr.internal.InternalSceneDslParser;
import hu.sze.aut.robotlabor.scene.description.services.SceneDslGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class SceneDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(SceneDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, SceneDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getRootElementAccess().getAlternatives(), "rule__RootElement__Alternatives");
			builder.put(grammarAccess.getModelAccess().getAlternatives(), "rule__Model__Alternatives");
			builder.put(grammarAccess.getMaterialAccess().getAlternatives(), "rule__Material__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
			builder.put(grammarAccess.getSceneAccess().getGroup(), "rule__Scene__Group__0");
			builder.put(grammarAccess.getSceneAccess().getGroup_4(), "rule__Scene__Group_4__0");
			builder.put(grammarAccess.getExternalModelAccess().getGroup(), "rule__ExternalModel__Group__0");
			builder.put(grammarAccess.getExternalModelAccess().getGroup_4(), "rule__ExternalModel__Group_4__0");
			builder.put(grammarAccess.getExternalModelAccess().getGroup_5(), "rule__ExternalModel__Group_5__0");
			builder.put(grammarAccess.getSphereAccess().getGroup(), "rule__Sphere__Group__0");
			builder.put(grammarAccess.getSphereAccess().getGroup_4(), "rule__Sphere__Group_4__0");
			builder.put(grammarAccess.getSphereAccess().getGroup_5(), "rule__Sphere__Group_5__0");
			builder.put(grammarAccess.getSphereAccess().getGroup_6(), "rule__Sphere__Group_6__0");
			builder.put(grammarAccess.getSphereAccess().getGroup_7(), "rule__Sphere__Group_7__0");
			builder.put(grammarAccess.getBoxAccess().getGroup(), "rule__Box__Group__0");
			builder.put(grammarAccess.getBoxAccess().getGroup_4(), "rule__Box__Group_4__0");
			builder.put(grammarAccess.getBoxAccess().getGroup_5(), "rule__Box__Group_5__0");
			builder.put(grammarAccess.getBoxAccess().getGroup_6(), "rule__Box__Group_6__0");
			builder.put(grammarAccess.getBoxAccess().getGroup_7(), "rule__Box__Group_7__0");
			builder.put(grammarAccess.getBoxAccess().getGroup_8(), "rule__Box__Group_8__0");
			builder.put(grammarAccess.getBoxAccess().getGroup_9(), "rule__Box__Group_9__0");
			builder.put(grammarAccess.getCylinderAccess().getGroup(), "rule__Cylinder__Group__0");
			builder.put(grammarAccess.getCylinderAccess().getGroup_4(), "rule__Cylinder__Group_4__0");
			builder.put(grammarAccess.getCylinderAccess().getGroup_5(), "rule__Cylinder__Group_5__0");
			builder.put(grammarAccess.getCylinderAccess().getGroup_6(), "rule__Cylinder__Group_6__0");
			builder.put(grammarAccess.getCylinderAccess().getGroup_7(), "rule__Cylinder__Group_7__0");
			builder.put(grammarAccess.getCylinderAccess().getGroup_8(), "rule__Cylinder__Group_8__0");
			builder.put(grammarAccess.getFloorAccess().getGroup(), "rule__Floor__Group__0");
			builder.put(grammarAccess.getFloorAccess().getGroup_4(), "rule__Floor__Group_4__0");
			builder.put(grammarAccess.getFloorAccess().getGroup_5(), "rule__Floor__Group_5__0");
			builder.put(grammarAccess.getFloorAccess().getGroup_6(), "rule__Floor__Group_6__0");
			builder.put(grammarAccess.getWallElementAccess().getGroup(), "rule__WallElement__Group__0");
			builder.put(grammarAccess.getWallElementAccess().getGroup_4(), "rule__WallElement__Group_4__0");
			builder.put(grammarAccess.getWallElementAccess().getGroup_5(), "rule__WallElement__Group_5__0");
			builder.put(grammarAccess.getWallElementAccess().getGroup_6(), "rule__WallElement__Group_6__0");
			builder.put(grammarAccess.getWallElementAccess().getGroup_7(), "rule__WallElement__Group_7__0");
			builder.put(grammarAccess.getWallElementAccess().getGroup_8(), "rule__WallElement__Group_8__0");
			builder.put(grammarAccess.getPlacementAccess().getGroup(), "rule__Placement__Group__0");
			builder.put(grammarAccess.getPlacementAccess().getGroup_2(), "rule__Placement__Group_2__0");
			builder.put(grammarAccess.getPlacementAccess().getGroup_3(), "rule__Placement__Group_3__0");
			builder.put(grammarAccess.getVec3Access().getGroup(), "rule__Vec3__Group__0");
			builder.put(grammarAccess.getVec3Access().getGroup_2(), "rule__Vec3__Group_2__0");
			builder.put(grammarAccess.getVec3Access().getGroup_3(), "rule__Vec3__Group_3__0");
			builder.put(grammarAccess.getVec3Access().getGroup_4(), "rule__Vec3__Group_4__0");
			builder.put(grammarAccess.getRotationAccess().getGroup(), "rule__Rotation__Group__0");
			builder.put(grammarAccess.getRotationAccess().getGroup_2(), "rule__Rotation__Group_2__0");
			builder.put(grammarAccess.getRotationAccess().getGroup_3(), "rule__Rotation__Group_3__0");
			builder.put(grammarAccess.getRotationAccess().getGroup_4(), "rule__Rotation__Group_4__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
			builder.put(grammarAccess.getPhysicParametersAccess().getGroup(), "rule__PhysicParameters__Group__0");
			builder.put(grammarAccess.getPhysicParametersAccess().getGroup_2(), "rule__PhysicParameters__Group_2__0");
			builder.put(grammarAccess.getColorAccess().getGroup(), "rule__Color__Group__0");
			builder.put(grammarAccess.getColorAccess().getGroup_3(), "rule__Color__Group_3__0");
			builder.put(grammarAccess.getColorAccess().getGroup_4(), "rule__Color__Group_4__0");
			builder.put(grammarAccess.getColorAccess().getGroup_5(), "rule__Color__Group_5__0");
			builder.put(grammarAccess.getColorAccess().getGroup_6(), "rule__Color__Group_6__0");
			builder.put(grammarAccess.getTextureAccess().getGroup(), "rule__Texture__Group__0");
			builder.put(grammarAccess.getTextureAccess().getGroup_3(), "rule__Texture__Group_3__0");
			builder.put(grammarAccess.getSceneAccess().getNameAssignment_2(), "rule__Scene__NameAssignment_2");
			builder.put(grammarAccess.getSceneAccess().getModelAssignment_4_2(), "rule__Scene__ModelAssignment_4_2");
			builder.put(grammarAccess.getSceneAccess().getModelAssignment_4_3(), "rule__Scene__ModelAssignment_4_3");
			builder.put(grammarAccess.getExternalModelAccess().getNameAssignment_2(), "rule__ExternalModel__NameAssignment_2");
			builder.put(grammarAccess.getExternalModelAccess().getPathAssignment_4_1(), "rule__ExternalModel__PathAssignment_4_1");
			builder.put(grammarAccess.getExternalModelAccess().getPlacementAssignment_5_1(), "rule__ExternalModel__PlacementAssignment_5_1");
			builder.put(grammarAccess.getSphereAccess().getNameAssignment_2(), "rule__Sphere__NameAssignment_2");
			builder.put(grammarAccess.getSphereAccess().getRadiusAssignment_4_1(), "rule__Sphere__RadiusAssignment_4_1");
			builder.put(grammarAccess.getSphereAccess().getPlacementAssignment_5_1(), "rule__Sphere__PlacementAssignment_5_1");
			builder.put(grammarAccess.getSphereAccess().getPhysicparametersAssignment_6_1(), "rule__Sphere__PhysicparametersAssignment_6_1");
			builder.put(grammarAccess.getSphereAccess().getMaterialAssignment_7_1(), "rule__Sphere__MaterialAssignment_7_1");
			builder.put(grammarAccess.getBoxAccess().getNameAssignment_2(), "rule__Box__NameAssignment_2");
			builder.put(grammarAccess.getBoxAccess().getWidthAssignment_4_1(), "rule__Box__WidthAssignment_4_1");
			builder.put(grammarAccess.getBoxAccess().getHeightAssignment_5_1(), "rule__Box__HeightAssignment_5_1");
			builder.put(grammarAccess.getBoxAccess().getDepthAssignment_6_1(), "rule__Box__DepthAssignment_6_1");
			builder.put(grammarAccess.getBoxAccess().getPlacementAssignment_7_1(), "rule__Box__PlacementAssignment_7_1");
			builder.put(grammarAccess.getBoxAccess().getPhysicparametersAssignment_8_1(), "rule__Box__PhysicparametersAssignment_8_1");
			builder.put(grammarAccess.getBoxAccess().getMaterialAssignment_9_1(), "rule__Box__MaterialAssignment_9_1");
			builder.put(grammarAccess.getCylinderAccess().getNameAssignment_2(), "rule__Cylinder__NameAssignment_2");
			builder.put(grammarAccess.getCylinderAccess().getRadiusAssignment_4_1(), "rule__Cylinder__RadiusAssignment_4_1");
			builder.put(grammarAccess.getCylinderAccess().getHeightAssignment_5_1(), "rule__Cylinder__HeightAssignment_5_1");
			builder.put(grammarAccess.getCylinderAccess().getPlacementAssignment_6_1(), "rule__Cylinder__PlacementAssignment_6_1");
			builder.put(grammarAccess.getCylinderAccess().getPhysicparametersAssignment_7_1(), "rule__Cylinder__PhysicparametersAssignment_7_1");
			builder.put(grammarAccess.getCylinderAccess().getMaterialAssignment_8_1(), "rule__Cylinder__MaterialAssignment_8_1");
			builder.put(grammarAccess.getFloorAccess().getNameAssignment_2(), "rule__Floor__NameAssignment_2");
			builder.put(grammarAccess.getFloorAccess().getPlacementAssignment_4_1(), "rule__Floor__PlacementAssignment_4_1");
			builder.put(grammarAccess.getFloorAccess().getPhysicparametersAssignment_5_1(), "rule__Floor__PhysicparametersAssignment_5_1");
			builder.put(grammarAccess.getFloorAccess().getMaterialAssignment_6_1(), "rule__Floor__MaterialAssignment_6_1");
			builder.put(grammarAccess.getWallElementAccess().getNameAssignment_2(), "rule__WallElement__NameAssignment_2");
			builder.put(grammarAccess.getWallElementAccess().getWidthAssignment_4_1(), "rule__WallElement__WidthAssignment_4_1");
			builder.put(grammarAccess.getWallElementAccess().getHeightAssignment_5_1(), "rule__WallElement__HeightAssignment_5_1");
			builder.put(grammarAccess.getWallElementAccess().getPlacementAssignment_6_1(), "rule__WallElement__PlacementAssignment_6_1");
			builder.put(grammarAccess.getWallElementAccess().getPhysicparametersAssignment_7_1(), "rule__WallElement__PhysicparametersAssignment_7_1");
			builder.put(grammarAccess.getWallElementAccess().getMaterialAssignment_8_1(), "rule__WallElement__MaterialAssignment_8_1");
			builder.put(grammarAccess.getPlacementAccess().getPositionAssignment_2_1(), "rule__Placement__PositionAssignment_2_1");
			builder.put(grammarAccess.getPlacementAccess().getRotationAssignment_3_1(), "rule__Placement__RotationAssignment_3_1");
			builder.put(grammarAccess.getVec3Access().getXAssignment_2_1(), "rule__Vec3__XAssignment_2_1");
			builder.put(grammarAccess.getVec3Access().getYAssignment_3_1(), "rule__Vec3__YAssignment_3_1");
			builder.put(grammarAccess.getVec3Access().getZAssignment_4_1(), "rule__Vec3__ZAssignment_4_1");
			builder.put(grammarAccess.getRotationAccess().getRollAssignment_2_1(), "rule__Rotation__RollAssignment_2_1");
			builder.put(grammarAccess.getRotationAccess().getPitchAssignment_3_1(), "rule__Rotation__PitchAssignment_3_1");
			builder.put(grammarAccess.getRotationAccess().getYawAssignment_4_1(), "rule__Rotation__YawAssignment_4_1");
			builder.put(grammarAccess.getPhysicParametersAccess().getMassAssignment_2_1(), "rule__PhysicParameters__MassAssignment_2_1");
			builder.put(grammarAccess.getColorAccess().getRedAssignment_3_1(), "rule__Color__RedAssignment_3_1");
			builder.put(grammarAccess.getColorAccess().getGreenAssignment_4_1(), "rule__Color__GreenAssignment_4_1");
			builder.put(grammarAccess.getColorAccess().getBlueAssignment_5_1(), "rule__Color__BlueAssignment_5_1");
			builder.put(grammarAccess.getColorAccess().getAlphaAssignment_6_1(), "rule__Color__AlphaAssignment_6_1");
			builder.put(grammarAccess.getTextureAccess().getPathAssignment_3_1(), "rule__Texture__PathAssignment_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private SceneDslGrammarAccess grammarAccess;

	@Override
	protected InternalSceneDslParser createParser() {
		InternalSceneDslParser result = new InternalSceneDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SceneDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SceneDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
