/*
 * generated by Xtext 2.23.0
 */
package hu.sze.aut.robot.description.scene.ui.tests;

import com.google.inject.Injector;
import hu.sze.aut.robot.description.scene.scenedsl.ui.internal.ScenedslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SceneDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ScenedslActivator.getInstance().getInjector("hu.sze.aut.robot.description.scene.SceneDsl");
	}

}
