/*
 * generated by Xtext 2.25.0
 */
package hu.sze.aut.robotlabor.scene.description.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SceneDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class RootElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.sze.aut.robotlabor.scene.description.SceneDsl.RootElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSceneParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cModelParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//RootElement returns RootElement:
		//    Scene | Model
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Scene | Model
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Scene
		public RuleCall getSceneParserRuleCall_0() { return cSceneParserRuleCall_0; }
		
		//Model
		public RuleCall getModelParserRuleCall_1() { return cModelParserRuleCall_1; }
	}
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.sze.aut.robotlabor.scene.description.SceneDsl.Model");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cExternalModelParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSphereParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cBoxParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cCylinderParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cFloorParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cWallElementParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//Model returns Model:
		//    ExternalModel | Sphere | Box | Cylinder | Floor | WallElement;
		@Override public ParserRule getRule() { return rule; }
		
		//ExternalModel | Sphere | Box | Cylinder | Floor | WallElement
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ExternalModel
		public RuleCall getExternalModelParserRuleCall_0() { return cExternalModelParserRuleCall_0; }
		
		//Sphere
		public RuleCall getSphereParserRuleCall_1() { return cSphereParserRuleCall_1; }
		
		//Box
		public RuleCall getBoxParserRuleCall_2() { return cBoxParserRuleCall_2; }
		
		//Cylinder
		public RuleCall getCylinderParserRuleCall_3() { return cCylinderParserRuleCall_3; }
		
		//Floor
		public RuleCall getFloorParserRuleCall_4() { return cFloorParserRuleCall_4; }
		
		//WallElement
		public RuleCall getWallElementParserRuleCall_5() { return cWallElementParserRuleCall_5; }
	}
	public class MaterialElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.sze.aut.robotlabor.scene.description.SceneDsl.Material");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cColorParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTextureParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Material returns Material:
		//    Color | Texture;
		@Override public ParserRule getRule() { return rule; }
		
		//Color | Texture
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Color
		public RuleCall getColorParserRuleCall_0() { return cColorParserRuleCall_0; }
		
		//Texture
		public RuleCall getTextureParserRuleCall_1() { return cTextureParserRuleCall_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.sze.aut.robotlabor.scene.description.SceneDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class SceneElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.sze.aut.robotlabor.scene.description.SceneDsl.Scene");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSceneAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSceneKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cModelsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cModelAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cModelModelParserRuleCall_4_2_0 = (RuleCall)cModelAssignment_4_2.eContents().get(0);
		private final Assignment cModelAssignment_4_3 = (Assignment)cGroup_4.eContents().get(3);
		private final RuleCall cModelModelParserRuleCall_4_3_0 = (RuleCall)cModelAssignment_4_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Scene returns Scene:
		//    {Scene}
		//    'scene'
		//    name=EString
		//    '{'
		//        ('models' '{' model+=Model (model+=Model)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Scene}
		//'scene'
		//name=EString
		//'{'
		//    ('models' '{' model+=Model (model+=Model)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Scene}
		public Action getSceneAction_0() { return cSceneAction_0; }
		
		//'scene'
		public Keyword getSceneKeyword_1() { return cSceneKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('models' '{' model+=Model (model+=Model)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'models'
		public Keyword getModelsKeyword_4_0() { return cModelsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//model+=Model
		public Assignment getModelAssignment_4_2() { return cModelAssignment_4_2; }
		
		//Model
		public RuleCall getModelModelParserRuleCall_4_2_0() { return cModelModelParserRuleCall_4_2_0; }
		
		//(model+=Model)*
		public Assignment getModelAssignment_4_3() { return cModelAssignment_4_3; }
		
		//Model
		public RuleCall getModelModelParserRuleCall_4_3_0() { return cModelModelParserRuleCall_4_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ExternalModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.sze.aut.robotlabor.scene.description.SceneDsl.ExternalModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cExternalModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cExternalmodelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPathKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPathAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPathEStringParserRuleCall_4_1_0 = (RuleCall)cPathAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPlacementKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPlacementAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPlacementPlacementParserRuleCall_5_1_0 = (RuleCall)cPlacementAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ExternalModel returns ExternalModel:
		//    {ExternalModel}
		//    'externalmodel'
		//    name=EString
		//    '{'
		//        ('path' path=EString)?
		//        ('placement' placement=Placement)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ExternalModel}
		//'externalmodel'
		//name=EString
		//'{'
		//    ('path' path=EString)?
		//    ('placement' placement=Placement)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{ExternalModel}
		public Action getExternalModelAction_0() { return cExternalModelAction_0; }
		
		//'externalmodel'
		public Keyword getExternalmodelKeyword_1() { return cExternalmodelKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('path' path=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'path'
		public Keyword getPathKeyword_4_0() { return cPathKeyword_4_0; }
		
		//path=EString
		public Assignment getPathAssignment_4_1() { return cPathAssignment_4_1; }
		
		//EString
		public RuleCall getPathEStringParserRuleCall_4_1_0() { return cPathEStringParserRuleCall_4_1_0; }
		
		//('placement' placement=Placement)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'placement'
		public Keyword getPlacementKeyword_5_0() { return cPlacementKeyword_5_0; }
		
		//placement=Placement
		public Assignment getPlacementAssignment_5_1() { return cPlacementAssignment_5_1; }
		
		//Placement
		public RuleCall getPlacementPlacementParserRuleCall_5_1_0() { return cPlacementPlacementParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class SphereElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.sze.aut.robotlabor.scene.description.SceneDsl.Sphere");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSphereAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSphereKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cRadiusKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cRadiusAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cRadiusEDoubleParserRuleCall_4_1_0 = (RuleCall)cRadiusAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPlacementKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPlacementAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPlacementPlacementParserRuleCall_5_1_0 = (RuleCall)cPlacementAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPhysicparametersKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPhysicparametersAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPhysicparametersPhysicParametersParserRuleCall_6_1_0 = (RuleCall)cPhysicparametersAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cMaterialKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cMaterialAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cMaterialMaterialParserRuleCall_7_1_0 = (RuleCall)cMaterialAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Sphere returns Sphere:
		//    {Sphere}
		//    'sphere'
		//    name=EString
		//    '{'
		//        ('radius' radius=EDouble)?
		//        ('placement' placement=Placement)?
		//        ('physicparameters' physicparameters=PhysicParameters )?
		//        ('material' material=Material)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Sphere}
		//'sphere'
		//name=EString
		//'{'
		//    ('radius' radius=EDouble)?
		//    ('placement' placement=Placement)?
		//    ('physicparameters' physicparameters=PhysicParameters )?
		//    ('material' material=Material)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Sphere}
		public Action getSphereAction_0() { return cSphereAction_0; }
		
		//'sphere'
		public Keyword getSphereKeyword_1() { return cSphereKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('radius' radius=EDouble)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'radius'
		public Keyword getRadiusKeyword_4_0() { return cRadiusKeyword_4_0; }
		
		//radius=EDouble
		public Assignment getRadiusAssignment_4_1() { return cRadiusAssignment_4_1; }
		
		//EDouble
		public RuleCall getRadiusEDoubleParserRuleCall_4_1_0() { return cRadiusEDoubleParserRuleCall_4_1_0; }
		
		//('placement' placement=Placement)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'placement'
		public Keyword getPlacementKeyword_5_0() { return cPlacementKeyword_5_0; }
		
		//placement=Placement
		public Assignment getPlacementAssignment_5_1() { return cPlacementAssignment_5_1; }
		
		//Placement
		public RuleCall getPlacementPlacementParserRuleCall_5_1_0() { return cPlacementPlacementParserRuleCall_5_1_0; }
		
		//('physicparameters' physicparameters=PhysicParameters )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'physicparameters'
		public Keyword getPhysicparametersKeyword_6_0() { return cPhysicparametersKeyword_6_0; }
		
		//physicparameters=PhysicParameters
		public Assignment getPhysicparametersAssignment_6_1() { return cPhysicparametersAssignment_6_1; }
		
		//PhysicParameters
		public RuleCall getPhysicparametersPhysicParametersParserRuleCall_6_1_0() { return cPhysicparametersPhysicParametersParserRuleCall_6_1_0; }
		
		//('material' material=Material)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'material'
		public Keyword getMaterialKeyword_7_0() { return cMaterialKeyword_7_0; }
		
		//material=Material
		public Assignment getMaterialAssignment_7_1() { return cMaterialAssignment_7_1; }
		
		//Material
		public RuleCall getMaterialMaterialParserRuleCall_7_1_0() { return cMaterialMaterialParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class BoxElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.sze.aut.robotlabor.scene.description.SceneDsl.Box");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBoxAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBoxKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cWidthKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cWidthAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cWidthEDoubleParserRuleCall_4_1_0 = (RuleCall)cWidthAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cHeightKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cHeightAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cHeightEDoubleParserRuleCall_5_1_0 = (RuleCall)cHeightAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDepthKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDepthAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDepthEDoubleParserRuleCall_6_1_0 = (RuleCall)cDepthAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPlacementKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cPlacementAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cPlacementPlacementParserRuleCall_7_1_0 = (RuleCall)cPlacementAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cPhysicparametersKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cPhysicparametersAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cPhysicparametersPhysicParametersParserRuleCall_8_1_0 = (RuleCall)cPhysicparametersAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cMaterialKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cMaterialAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cMaterialMaterialParserRuleCall_9_1_0 = (RuleCall)cMaterialAssignment_9_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Box returns Box:
		//    {Box}
		//    'box'
		//    name=EString
		//    '{'
		//        ('width' width=EDouble)?
		//        ('height' height=EDouble)?
		//        ('depth' depth=EDouble)?
		//        ('placement' placement=Placement)?
		//        ('physicparameters' physicparameters=PhysicParameters)?
		//        ('material' material=Material)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Box}
		//'box'
		//name=EString
		//'{'
		//    ('width' width=EDouble)?
		//    ('height' height=EDouble)?
		//    ('depth' depth=EDouble)?
		//    ('placement' placement=Placement)?
		//    ('physicparameters' physicparameters=PhysicParameters)?
		//    ('material' material=Material)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Box}
		public Action getBoxAction_0() { return cBoxAction_0; }
		
		//'box'
		public Keyword getBoxKeyword_1() { return cBoxKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('width' width=EDouble)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'width'
		public Keyword getWidthKeyword_4_0() { return cWidthKeyword_4_0; }
		
		//width=EDouble
		public Assignment getWidthAssignment_4_1() { return cWidthAssignment_4_1; }
		
		//EDouble
		public RuleCall getWidthEDoubleParserRuleCall_4_1_0() { return cWidthEDoubleParserRuleCall_4_1_0; }
		
		//('height' height=EDouble)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'height'
		public Keyword getHeightKeyword_5_0() { return cHeightKeyword_5_0; }
		
		//height=EDouble
		public Assignment getHeightAssignment_5_1() { return cHeightAssignment_5_1; }
		
		//EDouble
		public RuleCall getHeightEDoubleParserRuleCall_5_1_0() { return cHeightEDoubleParserRuleCall_5_1_0; }
		
		//('depth' depth=EDouble)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'depth'
		public Keyword getDepthKeyword_6_0() { return cDepthKeyword_6_0; }
		
		//depth=EDouble
		public Assignment getDepthAssignment_6_1() { return cDepthAssignment_6_1; }
		
		//EDouble
		public RuleCall getDepthEDoubleParserRuleCall_6_1_0() { return cDepthEDoubleParserRuleCall_6_1_0; }
		
		//('placement' placement=Placement)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'placement'
		public Keyword getPlacementKeyword_7_0() { return cPlacementKeyword_7_0; }
		
		//placement=Placement
		public Assignment getPlacementAssignment_7_1() { return cPlacementAssignment_7_1; }
		
		//Placement
		public RuleCall getPlacementPlacementParserRuleCall_7_1_0() { return cPlacementPlacementParserRuleCall_7_1_0; }
		
		//('physicparameters' physicparameters=PhysicParameters)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'physicparameters'
		public Keyword getPhysicparametersKeyword_8_0() { return cPhysicparametersKeyword_8_0; }
		
		//physicparameters=PhysicParameters
		public Assignment getPhysicparametersAssignment_8_1() { return cPhysicparametersAssignment_8_1; }
		
		//PhysicParameters
		public RuleCall getPhysicparametersPhysicParametersParserRuleCall_8_1_0() { return cPhysicparametersPhysicParametersParserRuleCall_8_1_0; }
		
		//('material' material=Material)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'material'
		public Keyword getMaterialKeyword_9_0() { return cMaterialKeyword_9_0; }
		
		//material=Material
		public Assignment getMaterialAssignment_9_1() { return cMaterialAssignment_9_1; }
		
		//Material
		public RuleCall getMaterialMaterialParserRuleCall_9_1_0() { return cMaterialMaterialParserRuleCall_9_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class CylinderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.sze.aut.robotlabor.scene.description.SceneDsl.Cylinder");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCylinderAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCylinderKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cRadiusKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cRadiusAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cRadiusEDoubleParserRuleCall_4_1_0 = (RuleCall)cRadiusAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cHeightKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cHeightAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cHeightEDoubleParserRuleCall_5_1_0 = (RuleCall)cHeightAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPlacementKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPlacementAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPlacementPlacementParserRuleCall_6_1_0 = (RuleCall)cPlacementAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPhysicparametersKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cPhysicparametersAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cPhysicparametersPhysicParametersParserRuleCall_7_1_0 = (RuleCall)cPhysicparametersAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cMaterialKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cMaterialAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cMaterialMaterialParserRuleCall_8_1_0 = (RuleCall)cMaterialAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Cylinder returns Cylinder:
		//    {Cylinder}
		//    'cylinder'
		//    name=EString
		//    '{'
		//        ('radius' radius=EDouble)?
		//        ('height' height=EDouble)?
		//        ('placement' placement=Placement)?
		//        ('physicparameters' physicparameters=PhysicParameters)?
		//        ('material' material=Material)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Cylinder}
		//'cylinder'
		//name=EString
		//'{'
		//    ('radius' radius=EDouble)?
		//    ('height' height=EDouble)?
		//    ('placement' placement=Placement)?
		//    ('physicparameters' physicparameters=PhysicParameters)?
		//    ('material' material=Material)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Cylinder}
		public Action getCylinderAction_0() { return cCylinderAction_0; }
		
		//'cylinder'
		public Keyword getCylinderKeyword_1() { return cCylinderKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('radius' radius=EDouble)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'radius'
		public Keyword getRadiusKeyword_4_0() { return cRadiusKeyword_4_0; }
		
		//radius=EDouble
		public Assignment getRadiusAssignment_4_1() { return cRadiusAssignment_4_1; }
		
		//EDouble
		public RuleCall getRadiusEDoubleParserRuleCall_4_1_0() { return cRadiusEDoubleParserRuleCall_4_1_0; }
		
		//('height' height=EDouble)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'height'
		public Keyword getHeightKeyword_5_0() { return cHeightKeyword_5_0; }
		
		//height=EDouble
		public Assignment getHeightAssignment_5_1() { return cHeightAssignment_5_1; }
		
		//EDouble
		public RuleCall getHeightEDoubleParserRuleCall_5_1_0() { return cHeightEDoubleParserRuleCall_5_1_0; }
		
		//('placement' placement=Placement)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'placement'
		public Keyword getPlacementKeyword_6_0() { return cPlacementKeyword_6_0; }
		
		//placement=Placement
		public Assignment getPlacementAssignment_6_1() { return cPlacementAssignment_6_1; }
		
		//Placement
		public RuleCall getPlacementPlacementParserRuleCall_6_1_0() { return cPlacementPlacementParserRuleCall_6_1_0; }
		
		//('physicparameters' physicparameters=PhysicParameters)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'physicparameters'
		public Keyword getPhysicparametersKeyword_7_0() { return cPhysicparametersKeyword_7_0; }
		
		//physicparameters=PhysicParameters
		public Assignment getPhysicparametersAssignment_7_1() { return cPhysicparametersAssignment_7_1; }
		
		//PhysicParameters
		public RuleCall getPhysicparametersPhysicParametersParserRuleCall_7_1_0() { return cPhysicparametersPhysicParametersParserRuleCall_7_1_0; }
		
		//('material' material=Material)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'material'
		public Keyword getMaterialKeyword_8_0() { return cMaterialKeyword_8_0; }
		
		//material=Material
		public Assignment getMaterialAssignment_8_1() { return cMaterialAssignment_8_1; }
		
		//Material
		public RuleCall getMaterialMaterialParserRuleCall_8_1_0() { return cMaterialMaterialParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class FloorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.sze.aut.robotlabor.scene.description.SceneDsl.Floor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFloorAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFloorKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPlacementKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPlacementAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPlacementPlacementParserRuleCall_4_1_0 = (RuleCall)cPlacementAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPhysicparametersKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPhysicparametersAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPhysicparametersPhysicParametersParserRuleCall_5_1_0 = (RuleCall)cPhysicparametersAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cMaterialKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cMaterialAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cMaterialMaterialParserRuleCall_6_1_0 = (RuleCall)cMaterialAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Floor returns Floor:
		//    {Floor}
		//    'floor'
		//    name=EString
		//    '{'
		//        ('placement' placement=Placement)?
		//        ('physicparameters' physicparameters=PhysicParameters)?
		//        ('material' material=Material)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Floor}
		//'floor'
		//name=EString
		//'{'
		//    ('placement' placement=Placement)?
		//    ('physicparameters' physicparameters=PhysicParameters)?
		//    ('material' material=Material)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Floor}
		public Action getFloorAction_0() { return cFloorAction_0; }
		
		//'floor'
		public Keyword getFloorKeyword_1() { return cFloorKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('placement' placement=Placement)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'placement'
		public Keyword getPlacementKeyword_4_0() { return cPlacementKeyword_4_0; }
		
		//placement=Placement
		public Assignment getPlacementAssignment_4_1() { return cPlacementAssignment_4_1; }
		
		//Placement
		public RuleCall getPlacementPlacementParserRuleCall_4_1_0() { return cPlacementPlacementParserRuleCall_4_1_0; }
		
		//('physicparameters' physicparameters=PhysicParameters)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'physicparameters'
		public Keyword getPhysicparametersKeyword_5_0() { return cPhysicparametersKeyword_5_0; }
		
		//physicparameters=PhysicParameters
		public Assignment getPhysicparametersAssignment_5_1() { return cPhysicparametersAssignment_5_1; }
		
		//PhysicParameters
		public RuleCall getPhysicparametersPhysicParametersParserRuleCall_5_1_0() { return cPhysicparametersPhysicParametersParserRuleCall_5_1_0; }
		
		//('material' material=Material)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'material'
		public Keyword getMaterialKeyword_6_0() { return cMaterialKeyword_6_0; }
		
		//material=Material
		public Assignment getMaterialAssignment_6_1() { return cMaterialAssignment_6_1; }
		
		//Material
		public RuleCall getMaterialMaterialParserRuleCall_6_1_0() { return cMaterialMaterialParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class WallElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.sze.aut.robotlabor.scene.description.SceneDsl.WallElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cWallElementAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cWallKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cWidthKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cWidthAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cWidthEDoubleParserRuleCall_4_1_0 = (RuleCall)cWidthAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cHeightKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cHeightAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cHeightEDoubleParserRuleCall_5_1_0 = (RuleCall)cHeightAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPlacementKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPlacementAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPlacementPlacementParserRuleCall_6_1_0 = (RuleCall)cPlacementAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPhysicparametersKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cPhysicparametersAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cPhysicparametersPhysicParametersParserRuleCall_7_1_0 = (RuleCall)cPhysicparametersAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cMaterialKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cMaterialAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cMaterialMaterialParserRuleCall_8_1_0 = (RuleCall)cMaterialAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//WallElement returns WallElement:
		//    {WallElement}
		//    'wall'
		//    name=EString
		//    '{'
		//        ('width' width=EDouble)?
		//        ('height' height=EDouble)?
		//        ('placement' placement=Placement)?
		//        ('physicparameters' physicparameters=PhysicParameters)?
		//        ('material' material=Material)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{WallElement}
		//'wall'
		//name=EString
		//'{'
		//    ('width' width=EDouble)?
		//    ('height' height=EDouble)?
		//    ('placement' placement=Placement)?
		//    ('physicparameters' physicparameters=PhysicParameters)?
		//    ('material' material=Material)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{WallElement}
		public Action getWallElementAction_0() { return cWallElementAction_0; }
		
		//'wall'
		public Keyword getWallKeyword_1() { return cWallKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('width' width=EDouble)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'width'
		public Keyword getWidthKeyword_4_0() { return cWidthKeyword_4_0; }
		
		//width=EDouble
		public Assignment getWidthAssignment_4_1() { return cWidthAssignment_4_1; }
		
		//EDouble
		public RuleCall getWidthEDoubleParserRuleCall_4_1_0() { return cWidthEDoubleParserRuleCall_4_1_0; }
		
		//('height' height=EDouble)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'height'
		public Keyword getHeightKeyword_5_0() { return cHeightKeyword_5_0; }
		
		//height=EDouble
		public Assignment getHeightAssignment_5_1() { return cHeightAssignment_5_1; }
		
		//EDouble
		public RuleCall getHeightEDoubleParserRuleCall_5_1_0() { return cHeightEDoubleParserRuleCall_5_1_0; }
		
		//('placement' placement=Placement)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'placement'
		public Keyword getPlacementKeyword_6_0() { return cPlacementKeyword_6_0; }
		
		//placement=Placement
		public Assignment getPlacementAssignment_6_1() { return cPlacementAssignment_6_1; }
		
		//Placement
		public RuleCall getPlacementPlacementParserRuleCall_6_1_0() { return cPlacementPlacementParserRuleCall_6_1_0; }
		
		//('physicparameters' physicparameters=PhysicParameters)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'physicparameters'
		public Keyword getPhysicparametersKeyword_7_0() { return cPhysicparametersKeyword_7_0; }
		
		//physicparameters=PhysicParameters
		public Assignment getPhysicparametersAssignment_7_1() { return cPhysicparametersAssignment_7_1; }
		
		//PhysicParameters
		public RuleCall getPhysicparametersPhysicParametersParserRuleCall_7_1_0() { return cPhysicparametersPhysicParametersParserRuleCall_7_1_0; }
		
		//('material' material=Material)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'material'
		public Keyword getMaterialKeyword_8_0() { return cMaterialKeyword_8_0; }
		
		//material=Material
		public Assignment getMaterialAssignment_8_1() { return cMaterialAssignment_8_1; }
		
		//Material
		public RuleCall getMaterialMaterialParserRuleCall_8_1_0() { return cMaterialMaterialParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class PlacementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.sze.aut.robotlabor.scene.description.SceneDsl.Placement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPlacementAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cPositionKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cPositionAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cPositionVec3ParserRuleCall_2_1_0 = (RuleCall)cPositionAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cRotationKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cRotationAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cRotationRotationParserRuleCall_3_1_0 = (RuleCall)cRotationAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Placement returns Placement:
		//    {Placement}
		//    '{'
		//        ('position' position=Vec3)?
		//        ('rotation' rotation=Rotation)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Placement}
		//'{'
		//    ('position' position=Vec3)?
		//    ('rotation' rotation=Rotation)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Placement}
		public Action getPlacementAction_0() { return cPlacementAction_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('position' position=Vec3)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'position'
		public Keyword getPositionKeyword_2_0() { return cPositionKeyword_2_0; }
		
		//position=Vec3
		public Assignment getPositionAssignment_2_1() { return cPositionAssignment_2_1; }
		
		//Vec3
		public RuleCall getPositionVec3ParserRuleCall_2_1_0() { return cPositionVec3ParserRuleCall_2_1_0; }
		
		//('rotation' rotation=Rotation)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'rotation'
		public Keyword getRotationKeyword_3_0() { return cRotationKeyword_3_0; }
		
		//rotation=Rotation
		public Assignment getRotationAssignment_3_1() { return cRotationAssignment_3_1; }
		
		//Rotation
		public RuleCall getRotationRotationParserRuleCall_3_1_0() { return cRotationRotationParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class Vec3Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.sze.aut.robotlabor.scene.description.SceneDsl.Vec3");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVec3Action_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cXKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cXAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cXEDoubleParserRuleCall_2_1_0 = (RuleCall)cXAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cYKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cYAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cYEDoubleParserRuleCall_3_1_0 = (RuleCall)cYAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cZKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cZAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cZEDoubleParserRuleCall_4_1_0 = (RuleCall)cZAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Vec3 returns Vec3:
		//    {Vec3}
		//    '{'
		//        ('x' x=EDouble)?
		//        ('y' y=EDouble)?
		//        ('z' z=EDouble)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Vec3}
		//'{'
		//    ('x' x=EDouble)?
		//    ('y' y=EDouble)?
		//    ('z' z=EDouble)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Vec3}
		public Action getVec3Action_0() { return cVec3Action_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('x' x=EDouble)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'x'
		public Keyword getXKeyword_2_0() { return cXKeyword_2_0; }
		
		//x=EDouble
		public Assignment getXAssignment_2_1() { return cXAssignment_2_1; }
		
		//EDouble
		public RuleCall getXEDoubleParserRuleCall_2_1_0() { return cXEDoubleParserRuleCall_2_1_0; }
		
		//('y' y=EDouble)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'y'
		public Keyword getYKeyword_3_0() { return cYKeyword_3_0; }
		
		//y=EDouble
		public Assignment getYAssignment_3_1() { return cYAssignment_3_1; }
		
		//EDouble
		public RuleCall getYEDoubleParserRuleCall_3_1_0() { return cYEDoubleParserRuleCall_3_1_0; }
		
		//('z' z=EDouble)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'z'
		public Keyword getZKeyword_4_0() { return cZKeyword_4_0; }
		
		//z=EDouble
		public Assignment getZAssignment_4_1() { return cZAssignment_4_1; }
		
		//EDouble
		public RuleCall getZEDoubleParserRuleCall_4_1_0() { return cZEDoubleParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class RotationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.sze.aut.robotlabor.scene.description.SceneDsl.Rotation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRotationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cRollKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cRollAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cRollEDoubleParserRuleCall_2_1_0 = (RuleCall)cRollAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cPitchKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cPitchAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cPitchEDoubleParserRuleCall_3_1_0 = (RuleCall)cPitchAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cYawKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cYawAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cYawEDoubleParserRuleCall_4_1_0 = (RuleCall)cYawAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Rotation returns Rotation:
		//    {Rotation}
		//    '{'
		//        ('roll' roll=EDouble)?
		//        ('pitch' pitch=EDouble)?
		//        ('yaw' yaw=EDouble)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Rotation}
		//'{'
		//    ('roll' roll=EDouble)?
		//    ('pitch' pitch=EDouble)?
		//    ('yaw' yaw=EDouble)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Rotation}
		public Action getRotationAction_0() { return cRotationAction_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('roll' roll=EDouble)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'roll'
		public Keyword getRollKeyword_2_0() { return cRollKeyword_2_0; }
		
		//roll=EDouble
		public Assignment getRollAssignment_2_1() { return cRollAssignment_2_1; }
		
		//EDouble
		public RuleCall getRollEDoubleParserRuleCall_2_1_0() { return cRollEDoubleParserRuleCall_2_1_0; }
		
		//('pitch' pitch=EDouble)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'pitch'
		public Keyword getPitchKeyword_3_0() { return cPitchKeyword_3_0; }
		
		//pitch=EDouble
		public Assignment getPitchAssignment_3_1() { return cPitchAssignment_3_1; }
		
		//EDouble
		public RuleCall getPitchEDoubleParserRuleCall_3_1_0() { return cPitchEDoubleParserRuleCall_3_1_0; }
		
		//('yaw' yaw=EDouble)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'yaw'
		public Keyword getYawKeyword_4_0() { return cYawKeyword_4_0; }
		
		//yaw=EDouble
		public Assignment getYawAssignment_4_1() { return cYawAssignment_4_1; }
		
		//EDouble
		public RuleCall getYawEDoubleParserRuleCall_4_1_0() { return cYawEDoubleParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.sze.aut.robotlabor.scene.description.SceneDsl.EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDouble returns ecore::EDouble:
		//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E'|'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E'|'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//('E'|'e')
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class PhysicParametersElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.sze.aut.robotlabor.scene.description.SceneDsl.PhysicParameters");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPhysicParametersAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cMassKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cMassAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cMassEDoubleParserRuleCall_2_1_0 = (RuleCall)cMassAssignment_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//PhysicParameters returns PhysicParameters:
		//    {PhysicParameters}
		//    '{'
		//        ('mass' mass=EDouble)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{PhysicParameters}
		//'{'
		//    ('mass' mass=EDouble)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{PhysicParameters}
		public Action getPhysicParametersAction_0() { return cPhysicParametersAction_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('mass' mass=EDouble)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'mass'
		public Keyword getMassKeyword_2_0() { return cMassKeyword_2_0; }
		
		//mass=EDouble
		public Assignment getMassAssignment_2_1() { return cMassAssignment_2_1; }
		
		//EDouble
		public RuleCall getMassEDoubleParserRuleCall_2_1_0() { return cMassEDoubleParserRuleCall_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class ColorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.sze.aut.robotlabor.scene.description.SceneDsl.Color");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cColorAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cColorKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cRedKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cRedAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cRedEDoubleParserRuleCall_3_1_0 = (RuleCall)cRedAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cGreenKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cGreenAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cGreenEDoubleParserRuleCall_4_1_0 = (RuleCall)cGreenAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cBlueKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cBlueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cBlueEDoubleParserRuleCall_5_1_0 = (RuleCall)cBlueAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cAlphaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cAlphaAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cAlphaEDoubleParserRuleCall_6_1_0 = (RuleCall)cAlphaAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Color returns Color:
		//    {Color}
		//    'color'
		//    '{'
		//        ('red' red=EDouble)?
		//        ('green' green=EDouble)?
		//        ('blue' blue=EDouble)?
		//        ('alpha' alpha=EDouble)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Color}
		//'color'
		//'{'
		//    ('red' red=EDouble)?
		//    ('green' green=EDouble)?
		//    ('blue' blue=EDouble)?
		//    ('alpha' alpha=EDouble)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Color}
		public Action getColorAction_0() { return cColorAction_0; }
		
		//'color'
		public Keyword getColorKeyword_1() { return cColorKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('red' red=EDouble)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'red'
		public Keyword getRedKeyword_3_0() { return cRedKeyword_3_0; }
		
		//red=EDouble
		public Assignment getRedAssignment_3_1() { return cRedAssignment_3_1; }
		
		//EDouble
		public RuleCall getRedEDoubleParserRuleCall_3_1_0() { return cRedEDoubleParserRuleCall_3_1_0; }
		
		//('green' green=EDouble)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'green'
		public Keyword getGreenKeyword_4_0() { return cGreenKeyword_4_0; }
		
		//green=EDouble
		public Assignment getGreenAssignment_4_1() { return cGreenAssignment_4_1; }
		
		//EDouble
		public RuleCall getGreenEDoubleParserRuleCall_4_1_0() { return cGreenEDoubleParserRuleCall_4_1_0; }
		
		//('blue' blue=EDouble)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'blue'
		public Keyword getBlueKeyword_5_0() { return cBlueKeyword_5_0; }
		
		//blue=EDouble
		public Assignment getBlueAssignment_5_1() { return cBlueAssignment_5_1; }
		
		//EDouble
		public RuleCall getBlueEDoubleParserRuleCall_5_1_0() { return cBlueEDoubleParserRuleCall_5_1_0; }
		
		//('alpha' alpha=EDouble)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'alpha'
		public Keyword getAlphaKeyword_6_0() { return cAlphaKeyword_6_0; }
		
		//alpha=EDouble
		public Assignment getAlphaAssignment_6_1() { return cAlphaAssignment_6_1; }
		
		//EDouble
		public RuleCall getAlphaEDoubleParserRuleCall_6_1_0() { return cAlphaEDoubleParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class TextureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.sze.aut.robotlabor.scene.description.SceneDsl.Texture");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTextureAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTextureKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cPathKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cPathAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cPathEStringParserRuleCall_3_1_0 = (RuleCall)cPathAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Texture returns Texture:
		//    {Texture}
		//    'texture'
		//    '{'
		//        ('path' path=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Texture}
		//'texture'
		//'{'
		//    ('path' path=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Texture}
		public Action getTextureAction_0() { return cTextureAction_0; }
		
		//'texture'
		public Keyword getTextureKeyword_1() { return cTextureKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('path' path=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'path'
		public Keyword getPathKeyword_3_0() { return cPathKeyword_3_0; }
		
		//path=EString
		public Assignment getPathAssignment_3_1() { return cPathAssignment_3_1; }
		
		//EString
		public RuleCall getPathEStringParserRuleCall_3_1_0() { return cPathEStringParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	
	
	private final RootElementElements pRootElement;
	private final ModelElements pModel;
	private final MaterialElements pMaterial;
	private final EStringElements pEString;
	private final SceneElements pScene;
	private final ExternalModelElements pExternalModel;
	private final SphereElements pSphere;
	private final BoxElements pBox;
	private final CylinderElements pCylinder;
	private final FloorElements pFloor;
	private final WallElementElements pWallElement;
	private final PlacementElements pPlacement;
	private final Vec3Elements pVec3;
	private final RotationElements pRotation;
	private final EDoubleElements pEDouble;
	private final PhysicParametersElements pPhysicParameters;
	private final ColorElements pColor;
	private final TextureElements pTexture;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SceneDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRootElement = new RootElementElements();
		this.pModel = new ModelElements();
		this.pMaterial = new MaterialElements();
		this.pEString = new EStringElements();
		this.pScene = new SceneElements();
		this.pExternalModel = new ExternalModelElements();
		this.pSphere = new SphereElements();
		this.pBox = new BoxElements();
		this.pCylinder = new CylinderElements();
		this.pFloor = new FloorElements();
		this.pWallElement = new WallElementElements();
		this.pPlacement = new PlacementElements();
		this.pVec3 = new Vec3Elements();
		this.pRotation = new RotationElements();
		this.pEDouble = new EDoubleElements();
		this.pPhysicParameters = new PhysicParametersElements();
		this.pColor = new ColorElements();
		this.pTexture = new TextureElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("hu.sze.aut.robotlabor.scene.description.SceneDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//RootElement returns RootElement:
	//    Scene | Model
	//;
	public RootElementElements getRootElementAccess() {
		return pRootElement;
	}
	
	public ParserRule getRootElementRule() {
		return getRootElementAccess().getRule();
	}
	
	//Model returns Model:
	//    ExternalModel | Sphere | Box | Cylinder | Floor | WallElement;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Material returns Material:
	//    Color | Texture;
	public MaterialElements getMaterialAccess() {
		return pMaterial;
	}
	
	public ParserRule getMaterialRule() {
		return getMaterialAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Scene returns Scene:
	//    {Scene}
	//    'scene'
	//    name=EString
	//    '{'
	//        ('models' '{' model+=Model (model+=Model)* '}' )?
	//    '}';
	public SceneElements getSceneAccess() {
		return pScene;
	}
	
	public ParserRule getSceneRule() {
		return getSceneAccess().getRule();
	}
	
	//ExternalModel returns ExternalModel:
	//    {ExternalModel}
	//    'externalmodel'
	//    name=EString
	//    '{'
	//        ('path' path=EString)?
	//        ('placement' placement=Placement)?
	//    '}';
	public ExternalModelElements getExternalModelAccess() {
		return pExternalModel;
	}
	
	public ParserRule getExternalModelRule() {
		return getExternalModelAccess().getRule();
	}
	
	//Sphere returns Sphere:
	//    {Sphere}
	//    'sphere'
	//    name=EString
	//    '{'
	//        ('radius' radius=EDouble)?
	//        ('placement' placement=Placement)?
	//        ('physicparameters' physicparameters=PhysicParameters )?
	//        ('material' material=Material)?
	//    '}';
	public SphereElements getSphereAccess() {
		return pSphere;
	}
	
	public ParserRule getSphereRule() {
		return getSphereAccess().getRule();
	}
	
	//Box returns Box:
	//    {Box}
	//    'box'
	//    name=EString
	//    '{'
	//        ('width' width=EDouble)?
	//        ('height' height=EDouble)?
	//        ('depth' depth=EDouble)?
	//        ('placement' placement=Placement)?
	//        ('physicparameters' physicparameters=PhysicParameters)?
	//        ('material' material=Material)?
	//    '}';
	public BoxElements getBoxAccess() {
		return pBox;
	}
	
	public ParserRule getBoxRule() {
		return getBoxAccess().getRule();
	}
	
	//Cylinder returns Cylinder:
	//    {Cylinder}
	//    'cylinder'
	//    name=EString
	//    '{'
	//        ('radius' radius=EDouble)?
	//        ('height' height=EDouble)?
	//        ('placement' placement=Placement)?
	//        ('physicparameters' physicparameters=PhysicParameters)?
	//        ('material' material=Material)?
	//    '}';
	public CylinderElements getCylinderAccess() {
		return pCylinder;
	}
	
	public ParserRule getCylinderRule() {
		return getCylinderAccess().getRule();
	}
	
	//Floor returns Floor:
	//    {Floor}
	//    'floor'
	//    name=EString
	//    '{'
	//        ('placement' placement=Placement)?
	//        ('physicparameters' physicparameters=PhysicParameters)?
	//        ('material' material=Material)?
	//    '}';
	public FloorElements getFloorAccess() {
		return pFloor;
	}
	
	public ParserRule getFloorRule() {
		return getFloorAccess().getRule();
	}
	
	//WallElement returns WallElement:
	//    {WallElement}
	//    'wall'
	//    name=EString
	//    '{'
	//        ('width' width=EDouble)?
	//        ('height' height=EDouble)?
	//        ('placement' placement=Placement)?
	//        ('physicparameters' physicparameters=PhysicParameters)?
	//        ('material' material=Material)?
	//    '}';
	public WallElementElements getWallElementAccess() {
		return pWallElement;
	}
	
	public ParserRule getWallElementRule() {
		return getWallElementAccess().getRule();
	}
	
	//Placement returns Placement:
	//    {Placement}
	//    '{'
	//        ('position' position=Vec3)?
	//        ('rotation' rotation=Rotation)?
	//    '}';
	public PlacementElements getPlacementAccess() {
		return pPlacement;
	}
	
	public ParserRule getPlacementRule() {
		return getPlacementAccess().getRule();
	}
	
	//Vec3 returns Vec3:
	//    {Vec3}
	//    '{'
	//        ('x' x=EDouble)?
	//        ('y' y=EDouble)?
	//        ('z' z=EDouble)?
	//    '}';
	public Vec3Elements getVec3Access() {
		return pVec3;
	}
	
	public ParserRule getVec3Rule() {
		return getVec3Access().getRule();
	}
	
	//Rotation returns Rotation:
	//    {Rotation}
	//    '{'
	//        ('roll' roll=EDouble)?
	//        ('pitch' pitch=EDouble)?
	//        ('yaw' yaw=EDouble)?
	//    '}';
	public RotationElements getRotationAccess() {
		return pRotation;
	}
	
	public ParserRule getRotationRule() {
		return getRotationAccess().getRule();
	}
	
	//EDouble returns ecore::EDouble:
	//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return pEDouble;
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}
	
	//PhysicParameters returns PhysicParameters:
	//    {PhysicParameters}
	//    '{'
	//        ('mass' mass=EDouble)?
	//    '}';
	public PhysicParametersElements getPhysicParametersAccess() {
		return pPhysicParameters;
	}
	
	public ParserRule getPhysicParametersRule() {
		return getPhysicParametersAccess().getRule();
	}
	
	//Color returns Color:
	//    {Color}
	//    'color'
	//    '{'
	//        ('red' red=EDouble)?
	//        ('green' green=EDouble)?
	//        ('blue' blue=EDouble)?
	//        ('alpha' alpha=EDouble)?
	//    '}';
	public ColorElements getColorAccess() {
		return pColor;
	}
	
	public ParserRule getColorRule() {
		return getColorAccess().getRule();
	}
	
	//Texture returns Texture:
	//    {Texture}
	//    'texture'
	//    '{'
	//        ('path' path=EString)?
	//    '}';
	public TextureElements getTextureAccess() {
		return pTexture;
	}
	
	public ParserRule getTextureRule() {
		return getTextureAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
