/*
 * generated by Xtext 2.23.0
 */
package hu.sze.aut.robotics.vehicle;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VehicleDslRuntimeModule extends AbstractVehicleDslRuntimeModule {
}
