/*
 * generated by Xtext 2.23.0
 */
package hu.sze.aut.robotics.vehicle;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class VehicleDslStandaloneSetup extends VehicleDslStandaloneSetupGenerated {

	public static void doSetup() {
		new VehicleDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
