/*
 * generated by Xtext 2.23.0
 */
package hu.sze.aut.robot.description.scene.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class SceneDslProposalProvider extends AbstractSceneDslProposalProvider {
}
