<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vehiclemodel" nsURI="http://aut.sze.hu/vehiclemodel" nsPrefix="vehiclemodel">
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle" eSuperTypes="#//RootElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="axes" upperBound="-1" eType="#//Axis"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wheelparameters" lowerBound="1"
        eType="#//WheelParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="physicalparameter" lowerBound="1"
        eType="#//PhysicalParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensorplacement" upperBound="-1"
        eType="#//SensorPlacement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simulationsetup" upperBound="-1"
        eType="#//SimulationSetup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wheel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wheelparameters" eType="#//WheelParameter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transmission_ratio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pose" eType="#//Pose" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WheelParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radius" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Axis">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radius" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="drive" upperBound="-1"
        eType="#//Drive" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//AxisType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="driven" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pose" eType="#//Pose" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topic_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsensor" upperBound="-1"
        eType="#//Sensor" containment="true" eOpposite="#//Sensor/sensor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" eType="#//Sensor"
        eOpposite="#//Sensor/subsensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Drive">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wheel" upperBound="-1"
        eType="#//Wheel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiDAR" eSuperTypes="#//Sensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min_distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="laser_count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="32"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="meas_per_rotation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="360"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="field_of_view" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="center_angle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Camera" eSuperTypes="#//Sensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="field_of_view" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="90.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quality" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="100"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min_distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color_format" eType="#//CameraColorFormat"
        defaultValueLiteral="Color"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image_width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image_height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baselength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Displacement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AxisType">
    <eLiterals name="NoSteer"/>
    <eLiterals name="AckermannSteer" value="1"/>
    <eLiterals name="Independent" value="2"/>
    <eLiterals name="Caster" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pose">
    <eStructuralFeatures xsi:type="ecore:EReference" name="displacement" eType="#//Displacement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rotation" eType="#//Rotation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pitch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yaw" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorPlacement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" lowerBound="1"
        eType="#//Sensor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pose" eType="#//Pose" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frame" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMU" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="GPS" eSuperTypes="#//Sensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="odometry" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LaserScanner" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="StereoCamera" eSuperTypes="#//Camera">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CameraColorFormat">
    <eLiterals name="GrayScale"/>
    <eLiterals name="Color" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Catalogue" eSuperTypes="#//RootElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" upperBound="-1"
        eType="#//Sensor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RootElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimulationSetup"/>
</ecore:EPackage>
