/*
 * generated by Xtext 2.23.0
 */
package hu.sze.aut.robot.kinematic;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class KinematicDslRuntimeModule extends AbstractKinematicDslRuntimeModule {
}
