/*
 * generated by Xtext 2.23.0
 */
package hu.sze.aut.robot.kinematic;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class KinematicDslStandaloneSetup extends KinematicDslStandaloneSetupGenerated {

	public static void doSetup() {
		new KinematicDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
