/*
 * generated by Xtext 2.25.0
 */
package hu.sze.aut.robotlabor.scene.description.ui;

import com.google.inject.Injector;
import hu.sze.aut.robotlabor.scene.description.scenedsl.ui.internal.ScenedslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SceneDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ScenedslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ScenedslActivator activator = ScenedslActivator.getInstance();
		return activator != null ? activator.getInjector(ScenedslActivator.HU_SZE_AUT_ROBOTLABOR_SCENE_DESCRIPTION_SCENEDSL) : null;
	}

}
