/*
 * generated by Xtext 2.25.0
 */
package hu.sze.aut.robotlabor.scene.description;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SceneDslRuntimeModule extends AbstractSceneDslRuntimeModule {
}
