/*
 * generated by Xtext 2.25.0
 */
package hu.sze.aut.robotlabor.scene.description;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SceneDslStandaloneSetup extends SceneDslStandaloneSetupGenerated {

	public static void doSetup() {
		new SceneDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
