/*
 * generated by Xtext 2.25.0
 */
package hu.sze.aut.robotlabor.scene.description.ide;


/**
 * Use this class to register ide components.
 */
public class SceneDslIdeModule extends AbstractSceneDslIdeModule {
}
